# Catppuccin Mocha for btop
# https://github.com/catppuccin/btop

theme[main_bg]="#1e1e2e"
theme[main_fg]="#cdd6f4"
theme[title]="#cdd6f4"
theme[hi_fg]="#f38ba8"
theme[selected_bg]="#585b70"
theme[selected_fg]="#f5e0dc"
theme[inactive_fg]="#45475a"
theme[graph_text]="#bac2de"
theme[meter_bg]="#45475a"
theme[proc_misc]="#94e2d5"
theme[cpu_box]="#89b4fa"
theme[mem_box]="#a6e3a1"
theme[net_box]="#f38ba8"
theme[proc_box]="#cba6f7"
theme[div_line]="#6c7086"

theme[temp_start]="#a6e3a1"
theme[temp_mid]="#f9e2af"
theme[temp_end]="#f38ba8"

theme[cpu_start]="#a6e3a1"
theme[cpu_mid]="#f9e2af"
theme[cpu_end]="#f38ba8"

theme[free_start]="#89b4fa"
theme[free_mid]=""
theme[free_end]=""

theme[cached_start]="#94e2d5"
theme[cached_mid]=""
theme[cached_end]=""

theme[available_start]="#f9e2af"
theme[available_mid]=""
theme[available_end]=""

theme[used_start]="#a6e3a1"
theme[used_mid]=""
theme[used_end]=""

theme[download_start]="#89b4fa"
theme[download_mid]=""
theme[download_end]="#cba6f7"

theme[upload_start]="#f38ba8"
theme[upload_mid]=""
theme[upload_end]="#fab387"

theme[process_start]="#a6e3a1"
theme[process_mid]="#f9e2af"
theme[process_end]="#f38ba8"
